apiVersion: apps/v1
kind: Deployment
metadata:
  name: charging-station-management-deployment
spec:
  selector:
    matchLabels:
      app: charging-station-management
  replicas: 3
  template:
    metadata:
      labels:
        app: charging-station-management
    spec:
      containers:
        - name: charging-station-management
          image: charging-station-management:1.0
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: charging-station-management-svc
  labels:
    name: charging-station-management
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: "TCP"
  selector:
    app: charging-station-management
  type: LoadBalancer